/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Currency = IDL.Variant({ 'inr' : IDL.Null, 'usd' : IDL.Null });
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const BankAccount = IDL.Record({
  'id' : IDL.Nat,
  'holderName' : IDL.Text,
  'user' : IDL.Principal,
  'bankName' : IDL.Text,
  'currency' : Currency,
  'isDefault' : IDL.Bool,
  'accountNumber' : IDL.Text,
  'routingOrIFSC' : IDL.Text,
});
export const Time = IDL.Int;
export const SellOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'bankAccountSnapshot' : BankAccount,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'payoutCurrency' : Currency,
  'adminNote' : IDL.Text,
  'updatedAt' : Time,
  'exchangeRateUsed' : IDL.Float64,
  'usdtAmount' : IDL.Float64,
  'payoutAmount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExchangeRates = IDL.Record({
  'usdRate' : IDL.Float64,
  'inrRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBankAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Currency, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'adminGetAllOrders' : IDL.Func([], [IDL.Vec(SellOrder)], ['query']),
  'adminUpdateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSellOrder' : IDL.Func([IDL.Float64, Currency, IDL.Nat], [IDL.Nat], []),
  'deleteBankAccount' : IDL.Func([IDL.Nat], [], []),
  'getBankAccount' : IDL.Func([IDL.Nat], [IDL.Opt(BankAccount)], ['query']),
  'getCallerBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
  'getCallerOrders' : IDL.Func([], [IDL.Vec(SellOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExchangeRates' : IDL.Func([], [ExchangeRates], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(SellOrder)], ['query']),
  'getUserBankAccounts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BankAccount)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setExchangeRate' : IDL.Func([Currency, IDL.Float64], [], []),
  'updateBankAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Currency, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Currency = IDL.Variant({ 'inr' : IDL.Null, 'usd' : IDL.Null });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const BankAccount = IDL.Record({
    'id' : IDL.Nat,
    'holderName' : IDL.Text,
    'user' : IDL.Principal,
    'bankName' : IDL.Text,
    'currency' : Currency,
    'isDefault' : IDL.Bool,
    'accountNumber' : IDL.Text,
    'routingOrIFSC' : IDL.Text,
  });
  const Time = IDL.Int;
  const SellOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'bankAccountSnapshot' : BankAccount,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'payoutCurrency' : Currency,
    'adminNote' : IDL.Text,
    'updatedAt' : Time,
    'exchangeRateUsed' : IDL.Float64,
    'usdtAmount' : IDL.Float64,
    'payoutAmount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExchangeRates = IDL.Record({
    'usdRate' : IDL.Float64,
    'inrRate' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBankAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Currency, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'adminGetAllOrders' : IDL.Func([], [IDL.Vec(SellOrder)], ['query']),
    'adminUpdateOrderStatus' : IDL.Func(
        [IDL.Nat, OrderStatus, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSellOrder' : IDL.Func(
        [IDL.Float64, Currency, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteBankAccount' : IDL.Func([IDL.Nat], [], []),
    'getBankAccount' : IDL.Func([IDL.Nat], [IDL.Opt(BankAccount)], ['query']),
    'getCallerBankAccounts' : IDL.Func([], [IDL.Vec(BankAccount)], ['query']),
    'getCallerOrders' : IDL.Func([], [IDL.Vec(SellOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExchangeRates' : IDL.Func([], [ExchangeRates], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(SellOrder)], ['query']),
    'getUserBankAccounts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BankAccount)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setExchangeRate' : IDL.Func([Currency, IDL.Float64], [], []),
    'updateBankAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Currency, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };