/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankAccount {
  'id' : bigint,
  'holderName' : string,
  'user' : Principal,
  'bankName' : string,
  'currency' : Currency,
  'isDefault' : boolean,
  'accountNumber' : string,
  'routingOrIFSC' : string,
}
export type Currency = { 'inr' : null } |
  { 'usd' : null };
export interface ExchangeRates { 'usdRate' : number, 'inrRate' : number }
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export interface SellOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'bankAccountSnapshot' : BankAccount,
  'createdAt' : Time,
  'user' : Principal,
  'payoutCurrency' : Currency,
  'adminNote' : string,
  'updatedAt' : Time,
  'exchangeRateUsed' : number,
  'usdtAmount' : number,
  'payoutAmount' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBankAccount' : ActorMethod<
    [string, string, string, string, Currency, boolean],
    bigint
  >,
  'adminGetAllOrders' : ActorMethod<[], Array<SellOrder>>,
  'adminUpdateOrderStatus' : ActorMethod<
    [bigint, OrderStatus, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSellOrder' : ActorMethod<[number, Currency, bigint], bigint>,
  'deleteBankAccount' : ActorMethod<[bigint], undefined>,
  'getBankAccount' : ActorMethod<[bigint], [] | [BankAccount]>,
  'getCallerBankAccounts' : ActorMethod<[], Array<BankAccount>>,
  'getCallerOrders' : ActorMethod<[], Array<SellOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExchangeRates' : ActorMethod<[], ExchangeRates>,
  'getOrderById' : ActorMethod<[bigint], [] | [SellOrder]>,
  'getUserBankAccounts' : ActorMethod<[Principal], Array<BankAccount>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setExchangeRate' : ActorMethod<[Currency, number], undefined>,
  'updateBankAccount' : ActorMethod<
    [bigint, string, string, string, string, Currency, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];